# Generated by Django 5.2.7 on 2025-11-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Пользователь", "verbose_name_plural": "Пользователи"},
        ),
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Введите ID чата в Telegram",
                max_length=50,
                null=True,
                verbose_name="ID чата в Telegram",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_recalled_daily",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте для ежедневного напоминания о заполнении дневника",
                verbose_name="Ежедневное напоминание",
            ),
        ),
    ]
