# Generated by Django 5.2.7 on 2025-10-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(default="Обычная заметка", max_length=255, verbose_name="Заголовок заметки"),
                ),
                ("content", models.TextField(verbose_name="Содержание")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="my_note/photo", verbose_name="Изображение"),
                ),
                ("is_important", models.BooleanField(default=False, verbose_name="Важная заметка")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания записи")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления записи")),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
                "ordering": ["-is_important", "-created_at"],
            },
        ),
    ]
