# Generated by Django 5.2.7 on 2025-10-29 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("my_note", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(fields=["title"], name="my_note_not_title_ef4718_idx"),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(fields=["content"], name="my_note_not_content_2f22c1_idx"),
        ),
    ]
