# Generated by Django 5.2.7 on 2025-10-30 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_note", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="image",
        ),
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(verbose_name="Содержание заметки"),
        ),
        migrations.CreateModel(
            name="NoteImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="my_note/photo", verbose_name="Изображение")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата добавления изображения")),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="my_note.note",
                        verbose_name="Заметка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение к заметке",
                "verbose_name_plural": "Изображения к заметкам",
                "ordering": ["created_at"],
            },
        ),
    ]
