# Generated by Django 5.2.7 on 2025-11-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_note", "0003_remove_note_image_alter_note_content_noteimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ["-created_at"], "verbose_name": "Запись", "verbose_name_plural": "Записи"},
        ),
    ]
